extends:
  - airbnb-base
  - prettier
  - prettier/standard
  - plugin:prettier/recommended
plugins:
  - import
  - prettier
env:
  es6: true
  node: true
rules:
  global-require: off
  import/no-dynamic-require: off
  prettier/prettier: error
